global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'gift shop backend'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:1999']

  - job_name: 'grafana'
    static_configs:
      - targets: ['host.docker.internal:3000']