name: CI/CD with Docker Compose

on: [push]

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose up -d --build

      - name: Deploy
        run: docker-compose down